language: node_js
sudo: false
matrix:
  include:
  - node_js: "6"
    env:
    - USE_SHIM=false
    - CXX=g++-4.8
  - node_js: "6"
    env:
    - USE_SHIM=true
    - CXX=g++-4.8
  - node_js: "5"
    env:
    - USE_SHIM=true
    - CXX=g++-4.8
  - node_js: "4"
    env:
    - USE_SHIM=true
    - CXX=g++-4.8
install:
  - npm install --no-optional
script:
  - bin/test
after_success:
  - npm run codecov
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8